// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillBridgeTutors.API.Data;

#nullable disable

namespace SkillBridgeTutors.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812145038_AddTeacherAndAssignment")]
    partial class AddTeacherAndAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillBridgeTutors.API.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.CallRecord", b =>
                {
                    b.Property<long>("CallRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CallRecordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CallRecordId"));

                    b.Property<string>("CallDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CallDirection");

                    b.Property<string>("CallStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CallStatus");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("DurationSeconds");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndedAt");

                    b.Property<long>("LeadId")
                        .HasColumnType("bigint")
                        .HasColumnName("LeadId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("RecordingUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RecordingUrl");

                    b.Property<string>("RetellCallId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RetellCallId");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CallRecordId");

                    b.HasIndex("LeadId");

                    b.ToTable("CallRecords");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.DemoBooking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BookingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("BookedAt");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CancellationReason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CancelledAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("LeadId")
                        .HasColumnType("bigint")
                        .HasColumnName("LeadId");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MeetingLink");

                    b.Property<long?>("RescheduledFromBookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("RescheduledFromBookingId");

                    b.Property<long>("SlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("SlotId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("TeacherId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("BookingId");

                    b.HasIndex("LeadId");

                    b.HasIndex("SlotId");

                    b.HasIndex("TeacherId");

                    b.ToTable("DemoBookings");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.DemoSlot", b =>
                {
                    b.Property<long>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SlotId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SlotId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndTime");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("IsAvailable");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartTime");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("SlotId");

                    b.ToTable("DemoSlots");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.Lead", b =>
                {
                    b.Property<long>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LeadId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LeadId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Query");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("LeadId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.Teacher", b =>
                {
                    b.Property<long>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TeacherId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Subjects");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.CallRecord", b =>
                {
                    b.HasOne("SkillBridgeTutors.API.Models.Lead", "Lead")
                        .WithMany("CallRecords")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.DemoBooking", b =>
                {
                    b.HasOne("SkillBridgeTutors.API.Models.Lead", "Lead")
                        .WithMany("DemoBookings")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillBridgeTutors.API.Models.DemoSlot", "DemoSlot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillBridgeTutors.API.Models.Teacher", "Teacher")
                        .WithMany("DemoBookings")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DemoSlot");

                    b.Navigation("Lead");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.Lead", b =>
                {
                    b.Navigation("CallRecords");

                    b.Navigation("DemoBookings");
                });

            modelBuilder.Entity("SkillBridgeTutors.API.Models.Teacher", b =>
                {
                    b.Navigation("DemoBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
